# Generated by Django 3.0.1 on 2020-01-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTicket', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talkies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('Rs', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieTicket.Movies')),
                ('talkies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieTicket.Talkies')),
            ],
        ),
    ]
