# Generated by Django 3.0.1 on 2020-02-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTicket', '0003_showtime_talkies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Blank', max_length=100)),
                ('st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieTicket.ShowTime')),
                ('talkies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieTicket.Talkies')),
            ],
        ),
    ]
